### ISSUE TITLE
Expose a public method/regex which we use of email validation.

### ISSUE THREAD

**Issue by puneet-sutar** [bigbinary/email_validator#1]
There are some Scenarios where we want to validate an email address which is not a model field. It would be nice if a method to validate an email or expose the regex used be exposed publicly.

This would ensure that email validation uses the same rules across a project.

**Comment by neerajsingh0101** [comment]
@puneet-sutar can you send a PR for this issue.

**Comment by puneet-sutar** [comment]
the pr was merged
